"""
★ GENERATE ±1 TEST LABELS for a dataset that ships without them.

    python -m scripts.make_test_negatives --dataset YAGO3-10
    python -m scripts.make_test_negatives --dataset YAGO3-10 --strategy type_consistent

WHY
---
WN11 and FB13 ship a `test.tsv` with a 4th column of +1 / -1. WN18RR and
YAGO3-10 do NOT -- KG-LLM used those for link/relation prediction, where the
true tail is all you need. Feed them to triple classification and every gold
answer becomes "No", so the model can score 100% by always answering No.

YAGO3-10 is otherwise the best graph we have for the type/rule question: its 37
relations are STRONGLY TYPED (`wasBornIn` Person->Place, `isCitizenOf`
Person->Country, `playsFor` Person->Club), which is exactly the structure WN11's
lexical relations lack. Generating the missing negatives unlocks it.

⚠️ THREE THINGS TO REPORT, NOT HIDE
-----------------------------------
1. **These negatives are ours, not the benchmark's.** Numbers are therefore NOT
   comparable to published YAGO3-10 results. All our comparisons are internal
   (A vs B vs C under one protocol), which is what the argument needs -- say so
   in every caption.
2. **The closed-world risk.** A corrupted triple may be TRUE but absent from the
   graph, in which case we label a fact as false. We filter against
   train ∪ valid ∪ test, so only facts missing from the ENTIRE graph can slip
   through. With 1M triples over 123k entities, a random corruption is almost
   surely false; a type-consistent one is more plausible and therefore riskier.
   The filtered count is reported.
3. **This is the same kind of object as WN11's labels.** WN11's negatives were
   also generated by corruption -- by its authors rather than by us. We are not
   inventing a new practice, only doing it visibly.
"""
from __future__ import annotations

import argparse
import random
from collections import defaultdict
from pathlib import Path

from src.data.loaders import load_kg
from src.utils.progress import track


def build_index(paths: list[Path]) -> set[tuple[str, str, str]]:
    """Every triple in the WHOLE graph — the filter against accidental truth."""
    known = set()
    for p in paths:
        if not p.exists():
            continue
        with p.open(encoding="utf-8") as f:
            for line in f:
                c = line.rstrip("\n").split("\t")
                if len(c) >= 3:
                    known.add((c[0], c[1], c[2]))
    return known


def relation_ranges(triples) -> tuple[dict, dict]:
    """
    Observed domain and range per relation.

    ★ On YAGO3-10 this IS the type system: entities seen as head of `wasBornIn`
    are people, entities seen as its tail are places. Type-consistent corruption
    samples a replacement from the same observed set, which produces a negative
    that cannot be rejected on type alone.
    """
    heads, tails = defaultdict(set), defaultdict(set)
    for t in triples:
        heads[t.relation].add(t.head)
        tails[t.relation].add(t.tail)
    return heads, tails


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", default="YAGO3-10")
    ap.add_argument("--root", default="data")
    ap.add_argument("--strategy", default="random",
                    choices=["random", "type_consistent"])
    ap.add_argument("--n-negatives", type=int, default=1,
                    help="per positive test triple (1 keeps the set balanced)")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--limit", type=int, default=0,
                    help="cap the number of positives kept (0 = all)")
    ap.add_argument("--out", default=None,
                    help="default: test.tsv is REPLACED and the original backed up")
    ns = ap.parse_args()

    d = Path(ns.root, ns.dataset)
    kg = load_kg(ns.dataset, ns.root)

    labelled = sum(1 for t in kg.test if t.label is not None)
    if labelled:
        raise SystemExit(
            f"{ns.dataset}/test.tsv already has {labelled:,} labelled rows. "
            f"Refusing to overwrite real benchmark labels with generated ones.")

    known = build_index([d / "train.tsv", d / "valid.tsv", d / "test.tsv",
                         d / "dev.tsv"])
    print(f"[neg] {ns.dataset}: {len(known):,} known triples across the whole graph")

    heads, tails = relation_ranges(kg.train)
    ents = list(kg.ent2txt)
    rng = random.Random(ns.seed)

    positives = kg.test[: ns.limit] if ns.limit else kg.test
    rows, skipped, accidental = [], 0, 0

    for t in track(positives, "generating negatives", total=len(positives)):
        rows.append((t.head, t.relation, t.tail, 1))
        for _ in range(ns.n_negatives):
            got = None
            for _try in range(60):
                corrupt_head = rng.random() < 0.5
                if ns.strategy == "type_consistent":
                    pool = list(heads[t.relation]) if corrupt_head else list(tails[t.relation])
                    if len(pool) < 2:
                        pool = ents
                else:
                    pool = ents
                e = rng.choice(pool)
                cand = (e, t.relation, t.tail) if corrupt_head else (t.head, t.relation, e)
                if cand[0] == cand[2]:
                    continue
                if cand in known:            # ⚠️ would be a TRUE fact labelled false
                    accidental += 1
                    continue
                got = cand
                break
            if got:
                rows.append((got[0], got[1], got[2], -1))
            else:
                skipped += 1

    out = Path(ns.out) if ns.out else d / "test.tsv"
    if out == d / "test.tsv":
        backup = d / "test.original.tsv"
        if not backup.exists():
            backup.write_text((d / "test.tsv").read_text(encoding="utf-8"),
                              encoding="utf-8")
            print(f"[neg] original preserved -> {backup}")

    with out.open("w", encoding="utf-8") as f:
        for h, r, t_, lab in rows:
            f.write(f"{h}\t{r}\t{t_}\t{lab}\n")

    n_pos = sum(1 for r in rows if r[3] == 1)
    n_neg = len(rows) - n_pos
    print(f"\n[neg] wrote {len(rows):,} rows -> {out}")
    print(f"      +{n_pos:,} / −{n_neg:,}  (balance {n_pos/len(rows):.1%})")
    print(f"      strategy: {ns.strategy}")
    print(f"      ⚠️ {accidental:,} candidate corruptions REJECTED because they "
          f"already exist in the graph")
    if skipped:
        print(f"      ⚠️ {skipped:,} positives got no negative after 60 attempts")
    print("\n★ REPORT THIS: these negatives are generated by us, not shipped with")
    print("  the benchmark. Numbers are not comparable to published YAGO3-10")
    print("  results; all comparisons must be internal and the protocol stated.")


if __name__ == "__main__":
    main()
